spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: test-route
          uri: http://httpbin.org
          predicates:
            - Path=/test/**
  redis:
    host: localhost
    port: 6379
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive: DEBUG
    org.springframework.boot.autoconfigure: DEBUG

eureka:
  client:
    enabled: false
  instance:
    enabled: false
